name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Grant excution permition for Gradle 
      run: chmod +x gradlew
    - name: Buid with Gradle
      run: ./gradlew build
    - name: Build and push to docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: yemanehadis/demo-app
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
